import { useEffect, useRef, useCallback, useState } from 'react';
import type {
  AIAgent,
  AgentActivity,
  AgentTriggerType,
  Person,
  Giving,
  Task,
  Interaction,
} from '../types';

interface AgentEngineProps {
  agents: AIAgent[];
  people: Person[];
  giving: Giving[];
  onUpdateAgent: (agentId: string, updates: Partial<AIAgent>) => void;
  onCreateTask?: (task: Omit<Task, 'id' | 'createdAt'>) => void;
  onAddTag?: (personId: string, tag: string) => void;
  onAddInteraction?: (interaction: Omit<Interaction, 'id' | 'createdAt'>) => void;
  onNotification?: (notification: AgentNotification) => void;
}

export interface AgentNotification {
  id: string;
  agentId: string;
  agentName: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning';
  timestamp: string;
  personId?: string;
  personName?: string;
}

interface DataSnapshot {
  givingIds: Set<string>;
  peopleCount: number;
}

export function useAgentEngine({
  agents,
  people,
  giving,
  onUpdateAgent,
  onCreateTask,
  onAddTag,
  onAddInteraction,
  onNotification,
}: AgentEngineProps) {
  const [notifications, setNotifications] = useState<AgentNotification[]>([]);
  const prevDataRef = useRef<DataSnapshot>({
    givingIds: new Set(),
    peopleCount: 0,
  });
  const lastBirthdayCheckRef = useRef<string>('');
  const isInitializedRef = useRef(false);

  // Check if today is someone's birthday
  const getTodaysBirthdays = useCallback((peopleList: Person[]): Person[] => {
    const today = new Date();
    const todayMonth = today.getMonth();
    const todayDate = today.getDate();

    return peopleList.filter((person) => {
      if (!person.birthDate) return false;
      const birthDate = new Date(person.birthDate);
      return birthDate.getMonth() === todayMonth && birthDate.getDate() === todayDate;
    });
  }, []);

  // Check for upcoming anniversaries (membership join date)
  const getTodaysAnniversaries = useCallback((peopleList: Person[]): Person[] => {
    const today = new Date();
    const todayMonth = today.getMonth();
    const todayDate = today.getDate();

    return peopleList.filter((person) => {
      if (!person.joinDate) return false;
      const joinDate = new Date(person.joinDate);
      return joinDate.getMonth() === todayMonth && joinDate.getDate() === todayDate;
    });
  }, []);

  // Execute agent action
  const executeAction = useCallback(
    (
      agent: AIAgent,
      actionType: string,
      actionConfig: Record<string, unknown>,
      targetPerson?: Person
    ): string => {
      switch (actionType) {
        case 'send_email':
          // Simulate email sending (would integrate with email service)
          console.log(`[Agent: ${agent.name}] Sending email to ${targetPerson?.email || 'N/A'}`);
          return `Email sent to ${targetPerson?.firstName || 'recipient'}`;

        case 'send_sms':
          // Simulate SMS sending (would integrate with SMS service)
          console.log(`[Agent: ${agent.name}] Sending SMS to ${targetPerson?.phone || 'N/A'}`);
          return `SMS sent to ${targetPerson?.firstName || 'recipient'}`;

        case 'create_task':
          if (onCreateTask && targetPerson) {
            const taskTitle = (actionConfig.title as string) || `Follow up with ${targetPerson.firstName}`;
            onCreateTask({
              personId: targetPerson.id,
              title: taskTitle,
              description: (actionConfig.description as string) || `Auto-generated by ${agent.name}`,
              dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
              completed: false,
              priority: (actionConfig.priority as 'high' | 'medium' | 'low') || 'medium',
              category: 'follow-up',
            });
            return `Task created: ${taskTitle}`;
          }
          return 'Task creation skipped';

        case 'add_tag':
          if (onAddTag && targetPerson) {
            const tag = (actionConfig.tag as string) || 'agent-processed';
            onAddTag(targetPerson.id, tag);
            return `Tag "${tag}" added`;
          }
          return 'Tag addition skipped';

        case 'notify_staff':
          const notification: AgentNotification = {
            id: `notif-${Date.now()}`,
            agentId: agent.id,
            agentName: agent.name,
            title: (actionConfig.title as string) || `${agent.name} Alert`,
            message: (actionConfig.message as string) || `Action triggered for ${targetPerson?.firstName || 'member'}`,
            type: 'info',
            timestamp: new Date().toISOString(),
            personId: targetPerson?.id,
            personName: targetPerson ? `${targetPerson.firstName} ${targetPerson.lastName}` : undefined,
          };
          setNotifications((prev) => [notification, ...prev].slice(0, 50));
          onNotification?.(notification);
          return 'Staff notified';

        case 'log_interaction':
          if (onAddInteraction && targetPerson) {
            const interactionType = (actionConfig.type as string) || 'note';
            onAddInteraction({
              personId: targetPerson.id,
              type: interactionType as Interaction['type'],
              content: (actionConfig.content as string) || `Auto-logged by ${agent.name}`,
              createdBy: agent.name,
            });
            return `Interaction logged`;
          }
          return 'Interaction logging skipped';

        case 'update_status':
          // Would update person status
          return `Status update queued`;

        default:
          return `Unknown action: ${actionType}`;
      }
    },
    [onCreateTask, onAddTag, onAddInteraction, onNotification]
  );

  // Run agent for a specific trigger
  const runAgent = useCallback(
    (
      agent: AIAgent,
      triggerType: AgentTriggerType,
      targetPerson?: Person,
      details?: string
    ) => {
      if (!agent.isEnabled || agent.status !== 'active') return;

      // Check if agent has this trigger enabled
      const trigger = agent.triggers?.find((t) => t.type === triggerType && t.isActive);
      if (!trigger) return;

      // Execute all actions in order
      const actionsTaken: string[] = [];
      const sortedActions = [...(agent.actions || [])].sort((a, b) => a.order - b.order);

      for (const action of sortedActions) {
        const result = executeAction(agent, action.type, action.config, targetPerson);
        actionsTaken.push(action.type);
        console.log(`[Agent: ${agent.name}] Action ${action.type}: ${result}`);
      }

      // Log activity
      const activity: AgentActivity = {
        id: `activity-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        agentId: agent.id,
        timestamp: new Date().toISOString(),
        triggerType,
        actionsTaken,
        targetPersonId: targetPerson?.id,
        targetPersonName: targetPerson ? `${targetPerson.firstName} ${targetPerson.lastName}` : undefined,
        status: 'success',
        details: details || `Processed ${triggerType} trigger`,
      };

      // Update agent with new activity and run counts
      const existingLog = agent.activityLog || [];
      onUpdateAgent(agent.id, {
        activityLog: [activity, ...existingLog].slice(0, 100),
        lastRun: new Date().toISOString(),
        runsToday: (agent.runsToday || 0) + 1,
        runsThisWeek: (agent.runsThisWeek || 0) + 1,
      });

      // Send notification if configured
      if (agent.config?.notifyOnRun) {
        const notification: AgentNotification = {
          id: `notif-${Date.now()}`,
          agentId: agent.id,
          agentName: agent.name,
          title: `${agent.name} Executed`,
          message: details || `Processed ${triggerType} for ${targetPerson?.firstName || 'member'}`,
          type: 'success',
          timestamp: new Date().toISOString(),
          personId: targetPerson?.id,
          personName: targetPerson ? `${targetPerson.firstName} ${targetPerson.lastName}` : undefined,
        };
        setNotifications((prev) => [notification, ...prev].slice(0, 50));
        onNotification?.(notification);
      }
    },
    [executeAction, onUpdateAgent, onNotification]
  );

  // Monitor for new donations
  useEffect(() => {
    if (!isInitializedRef.current) {
      // Initialize with current data
      prevDataRef.current = {
        givingIds: new Set(giving.map((g) => g.id)),
        peopleCount: people.length,
      };
      isInitializedRef.current = true;
      return;
    }

    // Check for new donations
    const currentGivingIds = new Set(giving.map((g) => g.id));
    const newDonations = giving.filter((g) => !prevDataRef.current.givingIds.has(g.id));

    for (const donation of newDonations) {
      const donor = people.find((p) => p.id === donation.personId);

      // Find agents with new_donation trigger
      for (const agent of agents) {
        runAgent(
          agent,
          'new_donation',
          donor,
          `New ${donation.fund} donation of $${donation.amount.toFixed(2)}`
        );

        // Check for giving_change trigger (large donations)
        const threshold = agent.config?.amountThreshold || 1000;
        if (donation.amount >= threshold) {
          runAgent(
            agent,
            'giving_change',
            donor,
            `Large donation alert: $${donation.amount.toFixed(2)} to ${donation.fund}`
          );
        }
      }
    }

    // Check for new members
    if (people.length > prevDataRef.current.peopleCount) {
      const newMemberCount = people.length - prevDataRef.current.peopleCount;
      // Assuming newest members are at the end or have recent join dates
      const potentialNewMembers = people.filter(
        (p) => p.status === 'visitor' || (p.joinDate && new Date(p.joinDate) > new Date(Date.now() - 24 * 60 * 60 * 1000))
      );

      for (const newMember of potentialNewMembers.slice(-newMemberCount)) {
        for (const agent of agents) {
          runAgent(
            agent,
            'new_member',
            newMember,
            `New member: ${newMember.firstName} ${newMember.lastName}`
          );
        }
      }
    }

    // Update snapshot
    prevDataRef.current = {
      givingIds: currentGivingIds,
      peopleCount: people.length,
    };
  }, [giving, people, agents, runAgent]);

  // Daily birthday/anniversary check
  useEffect(() => {
    const today = new Date().toDateString();

    // Only run once per day
    if (lastBirthdayCheckRef.current === today) return;
    lastBirthdayCheckRef.current = today;

    // Check birthdays
    const birthdayPeople = getTodaysBirthdays(people);
    for (const person of birthdayPeople) {
      for (const agent of agents) {
        runAgent(
          agent,
          'birthday',
          person,
          `Happy Birthday to ${person.firstName} ${person.lastName}!`
        );
      }
    }

    // Check anniversaries
    const anniversaryPeople = getTodaysAnniversaries(people);
    for (const person of anniversaryPeople) {
      const joinDate = new Date(person.joinDate!);
      const years = new Date().getFullYear() - joinDate.getFullYear();

      for (const agent of agents) {
        runAgent(
          agent,
          'anniversary',
          person,
          `${years} year membership anniversary for ${person.firstName} ${person.lastName}`
        );
      }
    }
  }, [people, agents, getTodaysBirthdays, getTodaysAnniversaries, runAgent]);

  // Manual trigger function for testing
  const triggerAgent = useCallback(
    (agentId: string, triggerType: AgentTriggerType, personId?: string) => {
      const agent = agents.find((a) => a.id === agentId);
      if (!agent) return;

      const person = personId ? people.find((p) => p.id === personId) : undefined;
      runAgent(agent, triggerType, person, `Manual trigger: ${triggerType}`);
    },
    [agents, people, runAgent]
  );

  // Clear a notification
  const clearNotification = useCallback((notificationId: string) => {
    setNotifications((prev) => prev.filter((n) => n.id !== notificationId));
  }, []);

  // Clear all notifications
  const clearAllNotifications = useCallback(() => {
    setNotifications([]);
  }, []);

  return {
    notifications,
    triggerAgent,
    clearNotification,
    clearAllNotifications,
  };
}
