import type { LeaderProfile } from '../../types';

export const DEMO_LEADERS: LeaderProfile[] = [
  {
    id: 'leader-1',
    displayName: 'Pastor Mike Davis',
    title: 'Senior Pastor — Marriage & Family',
    bio: 'Over 20 years of pastoral experience helping couples and families grow stronger in faith and love.',
    expertiseAreas: ['marriage', 'parenting', 'general'],
    credentials: ['M.Div — Dallas Theological Seminary', 'Certified Biblical Counselor'],
    yearsOfPractice: 22,
    personalityTraits: ['Warm', 'Patient', 'Scripture-focused'],
    spiritualFocusAreas: ['Prayer Ministry', 'Discipleship'],
    language: 'English',
    isVerified: true,
    isAvailable: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'leader-2',
    displayName: 'Pastor Sarah Johnson',
    title: 'Associate Pastor — Mental Health & Crisis',
    bio: 'Licensed counselor combining professional expertise with spiritual care for those facing anxiety, depression, and crisis.',
    expertiseAreas: ['anxiety-depression', 'crisis', 'grief'],
    credentials: ['Licensed Professional Counselor', 'M.A. Clinical Psychology'],
    yearsOfPractice: 15,
    personalityTraits: ['Empathetic', 'Calm', 'Encouraging'],
    spiritualFocusAreas: ['Healing Ministry', 'Intercessory Prayer'],
    language: 'English',
    isVerified: true,
    isAvailable: true,
    isActive: true,
    createdAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'leader-3',
    displayName: 'Deacon Robert Flores',
    title: 'Community Outreach — Financial & Recovery',
    bio: 'Former social worker with deep experience in financial counseling and addiction recovery support.',
    expertiseAreas: ['financial', 'addiction', 'crisis'],
    credentials: ['MSW — Columbia University', 'Certified Financial Counselor'],
    yearsOfPractice: 18,
    personalityTraits: ['Direct', 'Practical', 'Compassionate'],
    spiritualFocusAreas: ['Social Justice', 'Discipleship'],
    language: 'English',
    isVerified: true,
    isAvailable: false,
    isActive: true,
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'leader-4',
    displayName: 'Sister Grace Kim',
    title: 'Youth & Family Counselor',
    bio: 'Passionate about walking with young adults and families through life transitions and faith formation.',
    expertiseAreas: ['parenting', 'faith-questions', 'general'],
    credentials: ['M.A. Family Therapy', 'Youth Ministry Certificate'],
    yearsOfPractice: 10,
    personalityTraits: ['Energetic', 'Relatable', 'Insightful'],
    spiritualFocusAreas: ['Youth Ministry', 'Worship'],
    language: 'English',
    isVerified: true,
    isAvailable: true,
    isActive: true,
    createdAt: '2025-04-01T00:00:00Z',
  },
  {
    id: 'leader-5',
    displayName: 'Pastor James Wright',
    title: 'Recovery & Addiction Ministry',
    bio: 'Leading our Celebrate Recovery program with personal testimony and 12 years of ministry experience.',
    expertiseAreas: ['addiction', 'crisis', 'grief'],
    credentials: ['Certified Addiction Counselor', 'Celebrate Recovery Leader'],
    yearsOfPractice: 12,
    personalityTraits: ['Honest', 'Encouraging', 'Non-judgmental'],
    spiritualFocusAreas: ['Recovery Ministry', 'Men\'s Ministry'],
    language: 'English',
    isVerified: true,
    isAvailable: true,
    isActive: true,
    createdAt: '2025-02-15T00:00:00Z',
  },
];
